// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgimporornohgghyqswn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaW1wb3Jvcm5vaGdnaHlxc3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODM1ODgsImV4cCI6MjA1OTM1OTU4OH0.9z8FyC3S_6xMngK38dgyIXIsN0cfqYm3ng7wH6ttU-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);